# Generated by Django 3.0 on 2020-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='upload/photo')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='upload')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('nameOfClass', models.CharField(choices=[('Baobab', 'Baobab'), ('Iroko', 'Iroko'), ('Bamboo', 'Bamboo'), ('Acajou', 'Acajou')], default='Baobab', max_length=255)),
                ('firstNameOfMother', models.CharField(max_length=255)),
                ('lastNameOfMother', models.CharField(max_length=255)),
                ('phoneOfMother', models.CharField(max_length=255)),
                ('emailOfMother', models.EmailField(max_length=254)),
                ('firstNameOfFather', models.CharField(max_length=255)),
                ('lastNameOfFather', models.CharField(max_length=255)),
                ('phoneOfFather', models.CharField(max_length=255)),
                ('emailOfFather', models.EmailField(max_length=254)),
                ('allgeries', models.TextField(blank=True)),
                ('food_restriction', models.TextField(blank=True)),
                ('health_issue', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildDailyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ate', models.IntegerField()),
                ('ate_comment', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('nap_start_time', models.DateTimeField()),
                ('nap_end_time', models.DateTimeField()),
                ('is_bowel_move', models.BooleanField(default=False)),
                ('bowel_movement_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildApp.Child')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='food')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiblingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfSiblings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/pictures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='ChildApp.Child')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekName', models.CharField(choices=[('WEEK1', 'Week 1'), ('WEEK2', 'Week 2'), ('WEEK3', 'Week 3'), ('WEEK4', 'Week 4'), ('WEEK5', 'Week 5'), ('WEEK6', 'Week 6')], max_length=255)),
                ('dayName', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thrusday'), ('Friday', 'Friday')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foods', models.ManyToManyField(to='ChildApp.Food')),
            ],
        ),
        migrations.CreateModel(
            name='InjureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('taken_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('dailyinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injures', to='ChildApp.ChildDailyInformation')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencyContacts', to='ChildApp.Child')),
            ],
        ),
        migrations.AddField(
            model_name='childdailyinformation',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChildApp.MenuItem'),
        ),
    ]
