# Generated by Django 3.0 on 2020-10-09 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChildApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='sibling_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='ChildApp.SiblingGroup'),
        ),
        migrations.AddField(
            model_name='authperson',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authPersons', to='ChildApp.Child'),
        ),
    ]
