# Generated by Django 3.0 on 2020-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0002_auto_20201009_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='isFatherNone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='child',
            name='isMotherNone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='emailOfFather',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='emailOfMother',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='firstNameOfFather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='firstNameOfMother',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='lastNameOfFather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='lastNameOfMother',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='phoneOfFather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='phoneOfMother',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
