# Generated by Django 3.0 on 2021-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0004_auto_20210909_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nameOfClass',
            field=models.CharField(max_length=255),
        ),
    ]
