# Generated by Django 3.0 on 2021-09-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0005_removeclasschoices_ChildApp'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='flag_facebook',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_fin_contract',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_flyer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_friday_letter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_health_protocols',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_image_rights',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_instagram',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_interieur_rules',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_internet_sites',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_magazine',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_newsletter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_re_enrollment',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_responsibility_discharge',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_video',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='flag_yearbook',
            field=models.BooleanField(null=True),
        ),
    ]
