# Generated by Django 3.0 on 2021-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0006_auto_20210922_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='nameOfClass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
