# Generated by Django 3.0 on 2021-09-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0009_addSiblings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='picture',
            new_name='photo',
        ),
    ]
