# Generated by Django 3.0 on 2021-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0011_auto_20211007_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.FileField(upload_to='upload/pictures'),
        ),
    ]
