# Generated by Django 3.0 on 2021-10-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0013_auto_20211027_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
