# Generated by Django 3.0 on 2021-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0014_auto_20211027_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdailyinformation',
            name='nap_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='childdailyinformation',
            name='nap_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
