# Generated by Django 3.0 on 2021-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0015_auto_20211118_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='privacyRights',
            field=models.TextField(null=True),
        ),
    ]
