# Generated by Django 3.0 on 2021-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0016_auto_20211123_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyrights',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
