# Generated by Django 3.0 on 2021-11-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0017_auto_20211126_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyrights',
            name='name',
            field=models.TextField(),
        ),
    ]
