# Generated by Django 3.0 on 2021-11-26 12:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0019_auto_20211126_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='privacyRights',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='privacyrights',
            name='name',
            field=jsonfield.fields.JSONField(),
        ),
    ]
