# Generated by Django 3.0 on 2021-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0020_auto_20211126_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='privacyRights',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='privacyrights',
            name='name',
            field=models.TextField(),
        ),
    ]
