# Generated by Django 3.0 on 2021-11-26 14:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0021_auto_20211126_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyrights',
            name='name',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
