# Generated by Django 3.0 on 2021-11-26 14:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0022_auto_20211126_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='privacyRights',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
