# Generated by Django 3.0 on 2021-11-30 06:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0023_auto_20211126_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyrights',
            name='name',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
