# Generated by Django 3.0 on 2021-11-30 06:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0024_auto_20211130_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='privacyRights',
            field=jsonfield.fields.JSONField(default=[], null=True),
        ),
    ]
