# Generated by Django 3.0 on 2020-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('preset', 'Preset'), ('free', 'Free')], default='free', max_length=255)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('preset', 'Preset')], default='red', max_length=255)),
                ('presetType', models.CharField(blank=True, choices=[('toddler', 'Toddler'), ('kindergarten', 'Kindergarten')], max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('decline', 'Decline'), ('confirm', 'Confirm'), ('pending', 'Pending')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresetAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(choices=[('Baobab', 'Baobab'), ('Iroko', 'Iroko'), ('Bamboo', 'Bamboo'), ('Acajou', 'Acajou')], default='Baobab', max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PresetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(choices=[('Baobab', 'Baobab'), ('Iroko', 'Iroko'), ('Bamboo', 'Bamboo'), ('Acajou', 'Acajou')], default='Baobab', max_length=255)),
                ('duration', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='PresetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeDateTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('started', 'Started'), ('before start', 'Beforestart')], default='before start', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRangeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('presetItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeranges', to='AppointmentCenter.PresetItem')),
            ],
        ),
        migrations.AddField(
            model_name='presetitem',
            name='presetRecord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presetItems', to='AppointmentCenter.PresetRecord'),
        ),
    ]
