# Generated by Django 3.0 on 2020-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppointmentCenter', '0001_initial'),
        ('ChildApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetappointment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildApp.Child'),
        ),
        migrations.AddField(
            model_name='presetappointment',
            name='presetInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentCenter.PresetRecord'),
        ),
        migrations.AddField(
            model_name='presetappointment',
            name='timerange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_appointments', to='AppointmentCenter.TimeRangeItem'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ChildApp.Child'),
        ),
    ]
