# Generated by Django 3.0 on 2021-10-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCenter', '0006_auto_20211011_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetappointment',
            name='end',
        ),
        migrations.RemoveField(
            model_name='presetappointment',
            name='start',
        ),
    ]
