# Generated by Django 3.0 on 2021-10-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChildApp', '0012_auto_20211007_1027'),
        ('AppointmentCenter', '0008_auto_20211011_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetAppointmentSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentCenter.PresetAppointment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChildApp.Child')),
            ],
        ),
    ]
