# Generated by Django 3.0 on 2020-11-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangelibrary',
            name='donator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
