# Generated by Django 3.0 on 2021-09-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exchangelibrary_sattus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangelibrary',
            old_name='sattus',
            new_name='booked_status',
        ),
    ]
