# Generated by Django 3.0 on 2021-10-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210927_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangelibrary',
            old_name='created_at',
            new_name='booked_on',
        ),
        migrations.RenameField(
            model_name='exchangelibrary',
            old_name='updated_at',
            new_name='retured_on',
        ),
    ]
