# Generated by Django 3.0 on 2021-10-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_changedDatesInLibrary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangelibrary',
            old_name='retured_on',
            new_name='returned_on',
        ),
    ]
