# Generated by Django 3.0 on 2021-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_changedDatesInLibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangelibrary',
            name='booked_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exchangelibrary',
            name='booked_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangelibrary',
            name='returned_on',
            field=models.DateTimeField(null=True),
        ),
    ]
