# Generated by Django 3.0 on 2021-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_changedDatesInLibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangelibrary',
            name='booked_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchangelibrary',
            name='returned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
