# Generated by Django 3.0 on 2021-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211027_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangelibrary',
            name='picture',
            field=models.ImageField(null=True, upload_to='exchangelibrary'),
        ),
    ]
