# Generated by Django 3.0 on 2021-11-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211027_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooldocument',
            name='documentfor',
            field=models.CharField(default='All', max_length=255),
        ),
    ]
