# Generated by Django 3.0 on 2021-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211116_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniclub',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='miniclub',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
