# Generated by Django 3.0 on 2021-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniclub',
            name='date',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
