# Generated by Django 3.0 on 2021-11-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211126_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniclub',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='miniclub',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
