# Generated by Django 3.0 on 2021-11-26 14:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211126_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniclub',
            name='isPaid',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='miniclub',
            name='endDate',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='miniclub',
            name='startDate',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
