# Generated by Django 3.0 on 2020-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChildApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachedFiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('msgType', models.CharField(choices=[('Noraml', 'Normal'), ('BroadCast', 'Broadcast')], default='Noraml', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachedFiles', models.ManyToManyField(blank=True, related_name='messages', to='MessageApp.AttachedFile')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChildApp.Child')),
                ('headerMessage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MessageApp.Message')),
            ],
        ),
    ]
