# Generated by Django 3.0 on 2021-08-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_user_role1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
