# Generated by Django 3.0 on 2021-08-30 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_RemoveRoleField'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role1',
            new_name='role',
        ),
    ]
