# Generated by Django 3.0 on 2021-09-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_auto_20210902_1544'),
        ('UserApp', '0013_auto_20210901_0831'),
    ]

    operations = [
    ]
