# Generated by Django 3.0 on 2021-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_adddob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/photo'),
        ),
    ]
