# Generated by Django 3.0 on 2021-09-22 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCenter', '0004_appointment_addtionaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetappointment',
            name='presetInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppointmentCenter.PresetRecord'),
        ),
        migrations.AlterField(
            model_name='presetappointment',
            name='timerange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preset_appointments', to='AppointmentCenter.TimeRangeItem'),
        ),
    ]
