# Generated by Django 3.0 on 2021-10-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCenter', '0007_auto_20211011_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetappointment',
            name='endDateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='presetappointment',
            name='presetInfo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='presetappointment',
            name='startDateTime',
            field=models.DateTimeField(),
        ),
    ]
