# Generated by Django 3.0 on 2021-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCenter', '0011_auto_20211012_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetappointmentsessions',
            name='end',
        ),
        migrations.RemoveField(
            model_name='presetappointmentsessions',
            name='start',
        ),
        migrations.AddField(
            model_name='presetappointmentsessions',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='presetappointmentsessions',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='presetappointmentsessions',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='presetappointmentsessions',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
